# Auto-generated by deploy-pipeline.sh
# S3 backend configuration for Terraform state
bucket       = "terraform-state-saar-test"
key          = "saarcb2025/pipeline.tfstate"
region       = "il-central-1"
use_lockfile = true
