# Auto-generated by deploy-pipeline.sh from deployment-manifest.yaml
# Generated at: 2026-02-15T13:08:03Z

prefix             = "saarcb2025"
region             = "il-central-1"
create_new_repo    = true
repo_name          = "aws-genai-llm-chatbot-tf"
branch             = "main"
require_approval   = true
notification_email = "saar.adani@allcloud.io"
vpc_id             = "vpc-0bee666b81ca89734"
chatbot_stack_name = "saarcb2025GenAIChatBotStack"
subnet_ids         = [
  "subnet-0ff16c4f5cdf49bed",
  "subnet-06453b8fe50459fd0",
]
